# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: "windows-latest"

stages:
- stage: PipelineSqlServerTest
  displayName: Pipeline Sql Server TSQLt
  jobs: 
  - job: PipelineSqlServer
    steps:
    - task: PowerShell@2
      displayName: Run Script for sql server test - $(ProjectName) $(Version) 
      inputs:     
        filePath: './DevOpsRunTest.ps1'
      timeoutInMinutes: 10
      continueOnError: false  
      env:
        CONNECTIONSTRING: $(CONNECTIONSTRING)
    - task: PowerShell@2
      displayName: Run Next Step - $(ProjectName) $(Version)    
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          
          Write-Host "Print in case for success :)"
    - task: DotNetCoreCLI@2
      displayName: dotnet build --configuration $(BUILDCONFIGURATION)
      inputs:
        command: 'build'
        projects: './src'
        arguments: '--configuration $(BUILDCONFIGURATION)'
    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments:  '--configuration $(BUILDCONFIGURATION) --collect "Code coverage"'
 

    
