# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: "windows-latest"

stages:
- stage: PipelineSqlServerTest
  displayName: Pipeline Sql Server
  jobs: 
  - job: PipelineSqlServer
    steps:
    - task: AzureCLI@2
      displayName: Run Script for sql server test - $(ProjectName) $(Version)      
      inputs:
        azureSubscription: 'Visual Studio Enterprise($(AZSUBSCRIPTION))'
        scriptType: 'ps'
        scriptLocation: 'scriptPath'
        scriptPath: './DevOpsRunTest.ps1'
      timeoutInMinutes: 10
      continueOnError: false  
      env:
        CONNECTIONSTRING: $(CONNECTIONSTRING)

 

    
