# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: "windows-latest"

stages:
- stage: PipelineSqlServerTest
  displayName: Pipeline Sql Server
  jobs: 
  - job: Test
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(AZSUBSCRIPTION)
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          # Set firewall on server open for the agent
          $agentIp = (New-Object net.webclient).downloadstring("http://checkip.dyndns.com") -replace "[^\d\.]"
          az sql server firewall-rule create -g $(rg) -s $(server) -n test --start-ip-address $agentIp --end-ip-address $agentIp  
  - job: PipelineSqlServer
    steps:
    - task: PowerShell@2
      displayName: Run Script for sql server test - $(ProjectName) $(Version)
      inputs:
        filePath: './DevOpsRunTest.ps1'
      timeoutInMinutes: 10
      continueOnError: false
      env:
        CONNECTIONSTRING: $(CONNECTIONSTRING) 
